name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: golang:1.20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: go mod download

      - name: Install goreleaser
        run: |
          echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list
          apt update
          apt -y install goreleaser

      - name: Run goreleaser
        run: |
          cd $GITHUB_WORKSPACE
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          goreleaser