name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Install dependencies
        run: go mod download

      - name: Install goreleaser
        run: curl -sL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh

      - name: Run goreleaser
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          ./bin/goreleaser
